hippo/hippo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('hippoqueue/', include('hippoqueue.urls')),
    path('admin/', admin.site.urls),
]

hippo/hippoqueue/urls.py
from django.urls import path

from . import views

app_name = "hippoqueue"
urlpatterns = [
    path('', views.index, name='index'),
    path('oh/<str:teacher_name>', views.detail, name = 'detail'),
    path('oh/<str:teacher_name>/start/', views.start, name='start'),
    path('oh/<str:teacher_name>/add/', views.add, name='add'),
    path('oh/<str:teacher_name>/remove/<int:student_id>', views.remove, name='remove')
]

hippo/hippoqueue/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Teacher(models.Model):
    subject = models.CharField(max_length = 50)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

class OfficeHour(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete =
                                models.CASCADE)
    start = models.DateTimeField()
    length = models.IntegerField(default=1)

class Student(models.Model):
    officeHour = models.ForeignKey(OfficeHour, on_delete=
                                   models.CASCADE)
    fname = models.CharField(max_length = 50)
    lname = models.CharField(max_length = 50)
    email = models.CharField(max_length = 50)

hippo/hippoqueue/views.py
import datetime
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.template import loader
from django.urls import reverse
from django.shortcuts import get_object_or_404, render

from .models import Teacher, OfficeHour, Student
from django.contrib.auth.models import User

# Create your views here.
def index(request):
    return HttpResponse("Hello World")

def detail(request, teacher_name):
    template = loader.get_template('hippoqueue/detail.html')
    q = User.objects.filter(username=teacher_name)
    t = q[0].teacher
    if request.user.is_authenticated and request.user.username == teacher_name:
        template = loader.get_template('hippoqueue/detail.html')
        q = User.objects.filter(username=teacher_name)
        t = q[0].teacher
        if t.officehour_set.count() > 0:
            context = {
                'teacher_name':
                teacher_name,
                'teacher' :
                True,
                'started':
                True,
                'officehour':
                t.officehour_set.all()[0]
            }
        else:
            context = {
                'teacher_name':
                teacher_name,
                'teacher' :
                True
            }
        return HttpResponse(template.render(context, request))
    else:
        context = {
            'teacher_name':
            teacher_name,
            'officehour':
            t.officehour_set.all()[0]
        }
        return HttpResponse(template.render(context, request))

        

def start(request, teacher_name):
    if request.user.is_authenticated and request.user.username == teacher_name:
        q = User.objects.filter(username=teacher_name)
        t = q[0].teacher
        if t.officehour_set.count() == 0:
            t.officehour_set.create(start = datetime.datetime.now(), length = 2)
        else:
            print("Has office hours")
        return HttpResponse("Office hour started")
    else:
        return HttpResponseForbidden("You do not have permission to do that")

def add(request, teacher_name):
    print(request.POST['fname'])
    q = User.objects.filter(username=teacher_name)
    t = q[0].teacher
    oh = t.officehour_set.all()[0]
    oh.student_set.create(fname = request.POST['fname'], lname = request.POST['lname'])
    return HttpResponseRedirect(reverse('hippoqueue:detail', args=(teacher_name,)))

def remove(request, teacher_name, student_id):
    q = User.objects.filter(username=teacher_name)
    t = q[0].teacher
    oh = t.officehour_set.all()[0]
    student = Student.objects.filter(id = student_id, officeHour = oh)
    student.delete()
    return HttpResponseRedirect(reverse('hippoqueue:detail', args=(teacher_name,)))

hippo/hippoqueue/templates/hippoqueue/detail.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> OH Detail</title>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/bulma@0.9.0/css/bulma.min.css" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="https://raw.githubusercontent.com/grahamschock/hippoqueue/main/hippo/hippoqueue/static/hippoqueue/styles.css">
  </head>
  <div class="container">

    <nav class="navbar is-transparent">
      <div class="navbar-brand">
        <img src="{% static 'hippoqueue/imgs/logo.svg' %}" width="112" height="28">
                <div class="navbar-burger burger" data-target="navMenu">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <div id="navMenu" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="admin.html">
                      My OH
          </a>
                    <a class="navbar-item" href="admin.html">
                      Join OH
          </a>
                </div>

            </div>
    </nav>
  </div>

  <body>
    {% if teacher and started %}
    <div class = "container">
      <section class="hero">
        <form>
          <div class="hero-body has-text-centered">
            <h1 class="title">Hello, {{teacher_name}}</h1>
          </div>
          <div class="hero-body has-text-centered">
            <button class="button is-block is-primary is-medium is-rounded is-fullwidth is-danger" type="submit">
              Stop OH
            </button>
        </form>
        </div>
    </div>
    </section>
</div>

    <div class="container">
      <section class = "hero is-fullheight">
              <table class="table is-fullwidth">
                <tbody>
                  {% for student in officehour.student_set.all %}
                  <tr>
                    <td>
                      <form action="{% url 'hippoqueue:remove' teacher_name student.id %}" method="post">
                        {% csrf_token %}
                      {{student.fname}} {{student.lname}}
                    </td>
                    <td class="level-right">
            <button class="button is-small is-primary" type="submit"> Complete  </button>
                    </td>
                    </form>
                  </tr>
                    {% endfor %}
                </tbody>
              </table>

              </table>
    </section>
</div>
    {% elif teacher%}
    <div class = "container">
      <section class="hero is-fullheight">
        <form class = "box" action="{% url 'hippoqueue:start' teacher_name %}" method="post">
          {% csrf_token %}
          <div class="hero-body has-text-centered">
            <h1 class="title">Hello, {{teacher_name}}</h1>
          </div>
          <div class="hero-body has-text-centered">
            <h1 class="subtitle">You currently do not have any OH</h1>
          </div>

          <div class="hero-body has-text-centered">
            <button class="button is-block is-primary is-medium is-rounded is-fullwidth" type="submit">
              Start OH
            </button>
        </form>
        </div>
    </div>
    </section>
</div>
{% else %}
    <div class = "container">
      <section class="hero">
          <div class="hero-body has-text-centered">
            <h1 class="title">{{teacher_name}} Office Hours (Systems)</h1>
          </div>
          <progress class="progress" value="15" max="100">15%</progress>
    </section>
</div>

    <div class="container">
      <section class = "hero">
              <table class="table is-fullwidth">
                <tbody>
                  {% for student in officehour.student_set.all %}
                  <tr>
                    <td>
                      {{student.fname}} {{student.lname}}
                    </td>
                  </tr>
                    {% endfor %}
                </tbody>
              </table>
    </section>
    </div>

    <div class = "container">
      <section class = "hero has-text-centered">
        <form action="{% url 'hippoqueue:add' teacher_name %}" method="post">
          {% csrf_token %}
            <div class="field is-grouped">
              <div class="control">
                <input class="input is-medium is-rounded" type="name" placeholder="First name" autocomplete="First name" name="fname" required />
              </div>
              <div class="control">
                <input class="input is-medium is-rounded" type="name" placeholder="Last name" autocomplete="Last name" name="lname" required />
              </div>
            </div>
            <br />
            <button class="button is-block is-primary is-medium is-rounded is-fullwidth" type="submit">
              Add to Queue
            </button>
          </form>
      </section>
    </div>
{% endif %}
  </body>

<footer class="footer">
  <div class="content has-text-centered">
    Want to learn more? Interested in contributing? Check us out on <a href="https://github.com/grahamschock/hippoqueue">Github</a>

  </div>
</footer>

</html>